### ISSUE TITLE
SyntaxError: Block-scoped declarations  

### ISSUE THREAD

**Issue by impuls14** [phonegap-build/pgb-cli#11]
Error while running pgb command

usr/local/lib/node_modules/pgb-cli/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { const util=require('util'),session=require('./util/session'),parseArgs=require('./util/args'),colours=require('./util/colours'),version=require('../package.json').version,api=require('pgb-api')({events:process,headers:{"User-Agent":`pgb-cli/${version} node/${process.version} (${process.platform})`}});class PGB{constructor(){this.colours=colours,this.moduleVersion=version,this.api=api,this.session=session,this.cliOpts={flags:{version:'v',bare:'b',ascii:'a',json:'j',debug:'d',noprogress:'',help:'?h',force:'fy',completion:'',stdout:'s',nocolours:'c',nounlock:'',exit:'e',exitcode:''},aliases:{add:'new',create:'new',"add-key":'new-key',"create-key":'new-key',clone:'pull',delete:'rm',"delete-key":'rm-key',apps:'ls',list:'ls',"ls-keys":'keys',"list-keys":'keys',cordovas:'phonegaps',signin:'login',"sign-in":'login',signout:'logout',"sign-out":'logout',"unlock-key":'unlock',me:'whoami'}}}error(a){console.

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/pgb-cli/bin/pgb:2:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by goya** [comment]
it requires strict mode as the error states. 

if using the latest version use node >= 6
